package com.csj.gold.mobile.model;

import java.util.Date;

public class ProductTransactionsRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.tra_max_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long traMaxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.tra_min_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer traMinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.tra_add_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer traAddNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.tra_direction
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer traDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long prouductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_transactions_rule.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.id
     *
     * @return the value of product_transactions_rule.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.id
     *
     * @param id the value for product_transactions_rule.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.tra_max_num
     *
     * @return the value of product_transactions_rule.tra_max_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getTraMaxNum() {
        return traMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.tra_max_num
     *
     * @param traMaxNum the value for product_transactions_rule.tra_max_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTraMaxNum(Long traMaxNum) {
        this.traMaxNum = traMaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.tra_min_num
     *
     * @return the value of product_transactions_rule.tra_min_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTraMinNum() {
        return traMinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.tra_min_num
     *
     * @param traMinNum the value for product_transactions_rule.tra_min_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTraMinNum(Integer traMinNum) {
        this.traMinNum = traMinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.tra_add_num
     *
     * @return the value of product_transactions_rule.tra_add_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTraAddNum() {
        return traAddNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.tra_add_num
     *
     * @param traAddNum the value for product_transactions_rule.tra_add_num
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTraAddNum(Integer traAddNum) {
        this.traAddNum = traAddNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.tra_direction
     *
     * @return the value of product_transactions_rule.tra_direction
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTraDirection() {
        return traDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.tra_direction
     *
     * @param traDirection the value for product_transactions_rule.tra_direction
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTraDirection(Integer traDirection) {
        this.traDirection = traDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.prouduct_id
     *
     * @return the value of product_transactions_rule.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProuductId() {
        return prouductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.prouduct_id
     *
     * @param prouductId the value for product_transactions_rule.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProuductId(Long prouductId) {
        this.prouductId = prouductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.create_date
     *
     * @return the value of product_transactions_rule.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.create_date
     *
     * @param createDate the value for product_transactions_rule.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.create_user
     *
     * @return the value of product_transactions_rule.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.create_user
     *
     * @param createUser the value for product_transactions_rule.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.update_date
     *
     * @return the value of product_transactions_rule.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.update_date
     *
     * @param updateDate the value for product_transactions_rule.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.update_user
     *
     * @return the value of product_transactions_rule.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.update_user
     *
     * @param updateUser the value for product_transactions_rule.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.is_del
     *
     * @return the value of product_transactions_rule.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.is_del
     *
     * @param isDel the value for product_transactions_rule.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_transactions_rule.is_forbidden
     *
     * @return the value of product_transactions_rule.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_transactions_rule.is_forbidden
     *
     * @param isForbidden the value for product_transactions_rule.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}