package com.csj.gold.mobile.model;

import java.util.Date;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_introduct
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String productIntroduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_contract_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_start_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date productStartData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_end_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date productEndData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_introduct
     *
     * @return the value of product_info.product_introduct
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getProductIntroduct() {
        return productIntroduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_introduct
     *
     * @param productIntroduct the value for product_info.product_introduct
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductIntroduct(String productIntroduct) {
        this.productIntroduct = productIntroduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_contract_id
     *
     * @return the value of product_info.product_contract_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductContractId() {
        return productContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_contract_id
     *
     * @param productContractId the value for product_info.product_contract_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductContractId(Long productContractId) {
        this.productContractId = productContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_start_data
     *
     * @return the value of product_info.product_start_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getProductStartData() {
        return productStartData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_start_data
     *
     * @param productStartData the value for product_info.product_start_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductStartData(Date productStartData) {
        this.productStartData = productStartData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_end_data
     *
     * @return the value of product_info.product_end_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getProductEndData() {
        return productEndData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_end_data
     *
     * @param productEndData the value for product_info.product_end_data
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductEndData(Date productEndData) {
        this.productEndData = productEndData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_type
     *
     * @return the value of product_info.product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_type
     *
     * @param productType the value for product_info.product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductType(Long productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_status
     *
     * @return the value of product_info.product_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_status
     *
     * @param productStatus the value for product_info.product_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_date
     *
     * @return the value of product_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_date
     *
     * @param createDate the value for product_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_user
     *
     * @return the value of product_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_user
     *
     * @param createUser the value for product_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_date
     *
     * @return the value of product_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_date
     *
     * @param updateDate the value for product_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_user
     *
     * @return the value of product_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_user
     *
     * @param updateUser the value for product_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.is_forbidden
     *
     * @return the value of product_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.is_forbidden
     *
     * @param isForbidden the value for product_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.is_del
     *
     * @return the value of product_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.is_del
     *
     * @param isDel the value for product_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.version
     *
     * @return the value of product_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.version
     *
     * @param version the value for product_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}