package com.csj.gold.mobile.model;

import java.util.Date;

public class ProductPriceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_issued_price
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productIssuedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer productMoneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_sell_fee
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productSellFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_fee_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer productFeeUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_issued_total
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productIssuedTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_issued_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer productIssuedUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.product_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.id
     *
     * @return the value of product_price_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.id
     *
     * @param id the value for product_price_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_issued_price
     *
     * @return the value of product_price_info.product_issued_price
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductIssuedPrice() {
        return productIssuedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_issued_price
     *
     * @param productIssuedPrice the value for product_price_info.product_issued_price
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductIssuedPrice(Long productIssuedPrice) {
        this.productIssuedPrice = productIssuedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_money_type
     *
     * @return the value of product_price_info.product_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getProductMoneyType() {
        return productMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_money_type
     *
     * @param productMoneyType the value for product_price_info.product_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductMoneyType(Integer productMoneyType) {
        this.productMoneyType = productMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_sell_fee
     *
     * @return the value of product_price_info.product_sell_fee
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductSellFee() {
        return productSellFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_sell_fee
     *
     * @param productSellFee the value for product_price_info.product_sell_fee
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductSellFee(Long productSellFee) {
        this.productSellFee = productSellFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_fee_unit
     *
     * @return the value of product_price_info.product_fee_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getProductFeeUnit() {
        return productFeeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_fee_unit
     *
     * @param productFeeUnit the value for product_price_info.product_fee_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductFeeUnit(Integer productFeeUnit) {
        this.productFeeUnit = productFeeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_issued_total
     *
     * @return the value of product_price_info.product_issued_total
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductIssuedTotal() {
        return productIssuedTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_issued_total
     *
     * @param productIssuedTotal the value for product_price_info.product_issued_total
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductIssuedTotal(Long productIssuedTotal) {
        this.productIssuedTotal = productIssuedTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_issued_unit
     *
     * @return the value of product_price_info.product_issued_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getProductIssuedUnit() {
        return productIssuedUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_issued_unit
     *
     * @param productIssuedUnit the value for product_price_info.product_issued_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductIssuedUnit(Integer productIssuedUnit) {
        this.productIssuedUnit = productIssuedUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.product_id
     *
     * @return the value of product_price_info.product_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.product_id
     *
     * @param productId the value for product_price_info.product_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.version
     *
     * @return the value of product_price_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.version
     *
     * @param version the value for product_price_info.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.create_date
     *
     * @return the value of product_price_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.create_date
     *
     * @param createDate the value for product_price_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.create_user
     *
     * @return the value of product_price_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.create_user
     *
     * @param createUser the value for product_price_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.update_date
     *
     * @return the value of product_price_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.update_date
     *
     * @param updateDate the value for product_price_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.update_user
     *
     * @return the value of product_price_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.update_user
     *
     * @param updateUser the value for product_price_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.is_del
     *
     * @return the value of product_price_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.is_del
     *
     * @param isDel the value for product_price_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price_info.is_forbidden
     *
     * @return the value of product_price_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price_info.is_forbidden
     *
     * @param isForbidden the value for product_price_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}