package com.csj.gold.mobile.model;

import java.util.Date;

public class ProductInterestInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_income_payment_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pIncomePaymentUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_interest_way
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pInterestWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_interest_rate_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pInterestRateDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_interest_rate_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pInterestRateYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_interest_rate_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pInterestRateMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_interest_model
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pInterestModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_expiry_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pExpiryDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_expiry_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer pExpiryMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.p_expiry_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Byte pExpiryYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_interest_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.id
     *
     * @return the value of product_interest_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.id
     *
     * @param id the value for product_interest_info.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_income_payment_unit
     *
     * @return the value of product_interest_info.p_income_payment_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpIncomePaymentUnit() {
        return pIncomePaymentUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_income_payment_unit
     *
     * @param pIncomePaymentUnit the value for product_interest_info.p_income_payment_unit
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpIncomePaymentUnit(Integer pIncomePaymentUnit) {
        this.pIncomePaymentUnit = pIncomePaymentUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_interest_way
     *
     * @return the value of product_interest_info.p_interest_way
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpInterestWay() {
        return pInterestWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_interest_way
     *
     * @param pInterestWay the value for product_interest_info.p_interest_way
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpInterestWay(Integer pInterestWay) {
        this.pInterestWay = pInterestWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_interest_rate_day
     *
     * @return the value of product_interest_info.p_interest_rate_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpInterestRateDay() {
        return pInterestRateDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_interest_rate_day
     *
     * @param pInterestRateDay the value for product_interest_info.p_interest_rate_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpInterestRateDay(Integer pInterestRateDay) {
        this.pInterestRateDay = pInterestRateDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_interest_rate_year
     *
     * @return the value of product_interest_info.p_interest_rate_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpInterestRateYear() {
        return pInterestRateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_interest_rate_year
     *
     * @param pInterestRateYear the value for product_interest_info.p_interest_rate_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpInterestRateYear(Integer pInterestRateYear) {
        this.pInterestRateYear = pInterestRateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_interest_rate_month
     *
     * @return the value of product_interest_info.p_interest_rate_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpInterestRateMonth() {
        return pInterestRateMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_interest_rate_month
     *
     * @param pInterestRateMonth the value for product_interest_info.p_interest_rate_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpInterestRateMonth(Integer pInterestRateMonth) {
        this.pInterestRateMonth = pInterestRateMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_interest_model
     *
     * @return the value of product_interest_info.p_interest_model
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpInterestModel() {
        return pInterestModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_interest_model
     *
     * @param pInterestModel the value for product_interest_info.p_interest_model
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpInterestModel(Integer pInterestModel) {
        this.pInterestModel = pInterestModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_expiry_day
     *
     * @return the value of product_interest_info.p_expiry_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpExpiryDay() {
        return pExpiryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_expiry_day
     *
     * @param pExpiryDay the value for product_interest_info.p_expiry_day
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpExpiryDay(Integer pExpiryDay) {
        this.pExpiryDay = pExpiryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_expiry_month
     *
     * @return the value of product_interest_info.p_expiry_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getpExpiryMonth() {
        return pExpiryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_expiry_month
     *
     * @param pExpiryMonth the value for product_interest_info.p_expiry_month
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpExpiryMonth(Integer pExpiryMonth) {
        this.pExpiryMonth = pExpiryMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.p_expiry_year
     *
     * @return the value of product_interest_info.p_expiry_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Byte getpExpiryYear() {
        return pExpiryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.p_expiry_year
     *
     * @param pExpiryYear the value for product_interest_info.p_expiry_year
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setpExpiryYear(Byte pExpiryYear) {
        this.pExpiryYear = pExpiryYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.create_date
     *
     * @return the value of product_interest_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.create_date
     *
     * @param createDate the value for product_interest_info.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.create_user
     *
     * @return the value of product_interest_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.create_user
     *
     * @param createUser the value for product_interest_info.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.update_date
     *
     * @return the value of product_interest_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.update_date
     *
     * @param updateDate the value for product_interest_info.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.update_user
     *
     * @return the value of product_interest_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.update_user
     *
     * @param updateUser the value for product_interest_info.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.is_del
     *
     * @return the value of product_interest_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.is_del
     *
     * @param isDel the value for product_interest_info.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_interest_info.is_forbidden
     *
     * @return the value of product_interest_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_interest_info.is_forbidden
     *
     * @param isForbidden the value for product_interest_info.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}