package com.csj.gold.mobile.model;

import java.util.Date;

public class ScheduleHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.schedule_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer scheduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.shcedule_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date shceduleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.actived_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer activedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.shcedule_actived_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date shceduleActivedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.shcedule_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String shceduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_history.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.id
     *
     * @return the value of schedule_history.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.id
     *
     * @param id the value for schedule_history.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.schedule_type
     *
     * @return the value of schedule_history.schedule_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getScheduleType() {
        return scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.schedule_type
     *
     * @param scheduleType the value for schedule_history.schedule_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setScheduleType(Integer scheduleType) {
        this.scheduleType = scheduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.shcedule_date
     *
     * @return the value of schedule_history.shcedule_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getShceduleDate() {
        return shceduleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.shcedule_date
     *
     * @param shceduleDate the value for schedule_history.shcedule_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setShceduleDate(Date shceduleDate) {
        this.shceduleDate = shceduleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.actived_status
     *
     * @return the value of schedule_history.actived_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getActivedStatus() {
        return activedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.actived_status
     *
     * @param activedStatus the value for schedule_history.actived_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setActivedStatus(Integer activedStatus) {
        this.activedStatus = activedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.shcedule_actived_date
     *
     * @return the value of schedule_history.shcedule_actived_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getShceduleActivedDate() {
        return shceduleActivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.shcedule_actived_date
     *
     * @param shceduleActivedDate the value for schedule_history.shcedule_actived_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setShceduleActivedDate(Date shceduleActivedDate) {
        this.shceduleActivedDate = shceduleActivedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.shcedule_code
     *
     * @return the value of schedule_history.shcedule_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getShceduleCode() {
        return shceduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.shcedule_code
     *
     * @param shceduleCode the value for schedule_history.shcedule_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setShceduleCode(String shceduleCode) {
        this.shceduleCode = shceduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.create_date
     *
     * @return the value of schedule_history.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.create_date
     *
     * @param createDate the value for schedule_history.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.create_user
     *
     * @return the value of schedule_history.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.create_user
     *
     * @param createUser the value for schedule_history.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.update_date
     *
     * @return the value of schedule_history.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.update_date
     *
     * @param updateDate the value for schedule_history.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.update_user
     *
     * @return the value of schedule_history.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.update_user
     *
     * @param updateUser the value for schedule_history.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.is_forbidden
     *
     * @return the value of schedule_history.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.is_forbidden
     *
     * @param isForbidden the value for schedule_history.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.is_del
     *
     * @return the value of schedule_history.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.is_del
     *
     * @param isDel the value for schedule_history.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_history.version
     *
     * @return the value of schedule_history.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_history.version
     *
     * @param version the value for schedule_history.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}