package com.csj.gold.mobile.model;

import java.util.Date;

public class SysAccoutTransactions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.accout_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long accoutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.transaction_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long transactionMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.transaction_swift_no
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer transactionSwiftNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.transaction_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.order_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_accout_transactions.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.id
     *
     * @return the value of sys_accout_transactions.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.id
     *
     * @param id the value for sys_accout_transactions.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.accout_id
     *
     * @return the value of sys_accout_transactions.accout_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getAccoutId() {
        return accoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.accout_id
     *
     * @param accoutId the value for sys_accout_transactions.accout_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccoutId(Long accoutId) {
        this.accoutId = accoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.transaction_money
     *
     * @return the value of sys_accout_transactions.transaction_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getTransactionMoney() {
        return transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.transaction_money
     *
     * @param transactionMoney the value for sys_accout_transactions.transaction_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTransactionMoney(Long transactionMoney) {
        this.transactionMoney = transactionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.transaction_swift_no
     *
     * @return the value of sys_accout_transactions.transaction_swift_no
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTransactionSwiftNo() {
        return transactionSwiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.transaction_swift_no
     *
     * @param transactionSwiftNo the value for sys_accout_transactions.transaction_swift_no
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTransactionSwiftNo(Integer transactionSwiftNo) {
        this.transactionSwiftNo = transactionSwiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.transaction_type
     *
     * @return the value of sys_accout_transactions.transaction_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.transaction_type
     *
     * @param transactionType the value for sys_accout_transactions.transaction_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.order_number
     *
     * @return the value of sys_accout_transactions.order_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.order_number
     *
     * @param orderNumber the value for sys_accout_transactions.order_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.create_date
     *
     * @return the value of sys_accout_transactions.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.create_date
     *
     * @param createDate the value for sys_accout_transactions.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.update_date
     *
     * @return the value of sys_accout_transactions.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.update_date
     *
     * @param updateDate the value for sys_accout_transactions.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.create_user
     *
     * @return the value of sys_accout_transactions.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.create_user
     *
     * @param createUser the value for sys_accout_transactions.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.update_user
     *
     * @return the value of sys_accout_transactions.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.update_user
     *
     * @param updateUser the value for sys_accout_transactions.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.is_del
     *
     * @return the value of sys_accout_transactions.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.is_del
     *
     * @param isDel the value for sys_accout_transactions.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_accout_transactions.is_forbidden
     *
     * @return the value of sys_accout_transactions.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_accout_transactions.is_forbidden
     *
     * @param isForbidden the value for sys_accout_transactions.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}