package com.csj.gold.mobile.model;

import java.util.Date;

public class SysAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_total_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long accountTotalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer accountMoneyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.account_user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long accountUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.id
     *
     * @return the value of sys_account.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.id
     *
     * @param id the value for sys_account.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_code
     *
     * @return the value of sys_account.account_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_code
     *
     * @param accountCode the value for sys_account.account_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountCode(Integer accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_total_money
     *
     * @return the value of sys_account.account_total_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getAccountTotalMoney() {
        return accountTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_total_money
     *
     * @param accountTotalMoney the value for sys_account.account_total_money
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountTotalMoney(Long accountTotalMoney) {
        this.accountTotalMoney = accountTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_type
     *
     * @return the value of sys_account.account_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_type
     *
     * @param accountType the value for sys_account.account_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_money_type
     *
     * @return the value of sys_account.account_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getAccountMoneyType() {
        return accountMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_money_type
     *
     * @param accountMoneyType the value for sys_account.account_money_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountMoneyType(Integer accountMoneyType) {
        this.accountMoneyType = accountMoneyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_status
     *
     * @return the value of sys_account.account_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_status
     *
     * @param accountStatus the value for sys_account.account_status
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.account_user_id
     *
     * @return the value of sys_account.account_user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getAccountUserId() {
        return accountUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.account_user_id
     *
     * @param accountUserId the value for sys_account.account_user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setAccountUserId(Long accountUserId) {
        this.accountUserId = accountUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.is_del
     *
     * @return the value of sys_account.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.is_del
     *
     * @param isDel the value for sys_account.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.is_forbidden
     *
     * @return the value of sys_account.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.is_forbidden
     *
     * @param isForbidden the value for sys_account.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.create_date
     *
     * @return the value of sys_account.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.create_date
     *
     * @param createDate the value for sys_account.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.update_date
     *
     * @return the value of sys_account.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.update_date
     *
     * @param updateDate the value for sys_account.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.update_user
     *
     * @return the value of sys_account.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.update_user
     *
     * @param updateUser the value for sys_account.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.create_user
     *
     * @return the value of sys_account.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.create_user
     *
     * @param createUser the value for sys_account.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.version
     *
     * @return the value of sys_account.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.version
     *
     * @param version the value for sys_account.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}