package com.csj.gold.mobile.model;

import java.util.Date;

public class SysContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.contact_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String contactTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.file_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.tontact_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer tontactType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_contact.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.id
     *
     * @return the value of sys_contact.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.id
     *
     * @param id the value for sys_contact.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.contact_title
     *
     * @return the value of sys_contact.contact_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getContactTitle() {
        return contactTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.contact_title
     *
     * @param contactTitle the value for sys_contact.contact_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.file_id
     *
     * @return the value of sys_contact.file_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.file_id
     *
     * @param fileId the value for sys_contact.file_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.tontact_type
     *
     * @return the value of sys_contact.tontact_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTontactType() {
        return tontactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.tontact_type
     *
     * @param tontactType the value for sys_contact.tontact_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTontactType(Integer tontactType) {
        this.tontactType = tontactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.create_date
     *
     * @return the value of sys_contact.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.create_date
     *
     * @param createDate the value for sys_contact.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.create_user
     *
     * @return the value of sys_contact.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.create_user
     *
     * @param createUser the value for sys_contact.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.update_date
     *
     * @return the value of sys_contact.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.update_date
     *
     * @param updateDate the value for sys_contact.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.update_user
     *
     * @return the value of sys_contact.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.update_user
     *
     * @param updateUser the value for sys_contact.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.is_del
     *
     * @return the value of sys_contact.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.is_del
     *
     * @param isDel the value for sys_contact.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_contact.is_forbidden
     *
     * @return the value of sys_contact.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_contact.is_forbidden
     *
     * @param isForbidden the value for sys_contact.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}