package com.csj.gold.mobile.model;

import java.util.Date;

public class SysDictionaryType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.type_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.type_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer typePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_type.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.id
     *
     * @return the value of sys_dictionary_type.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.id
     *
     * @param id the value for sys_dictionary_type.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.type_name
     *
     * @return the value of sys_dictionary_type.type_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.type_name
     *
     * @param typeName the value for sys_dictionary_type.type_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.type_pid
     *
     * @return the value of sys_dictionary_type.type_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getTypePid() {
        return typePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.type_pid
     *
     * @param typePid the value for sys_dictionary_type.type_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setTypePid(Integer typePid) {
        this.typePid = typePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.remark
     *
     * @return the value of sys_dictionary_type.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.remark
     *
     * @param remark the value for sys_dictionary_type.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.create_date
     *
     * @return the value of sys_dictionary_type.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.create_date
     *
     * @param createDate the value for sys_dictionary_type.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.create_user
     *
     * @return the value of sys_dictionary_type.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.create_user
     *
     * @param createUser the value for sys_dictionary_type.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.update_date
     *
     * @return the value of sys_dictionary_type.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.update_date
     *
     * @param updateDate the value for sys_dictionary_type.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.update_user
     *
     * @return the value of sys_dictionary_type.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.update_user
     *
     * @param updateUser the value for sys_dictionary_type.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.is_del
     *
     * @return the value of sys_dictionary_type.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.is_del
     *
     * @param isDel the value for sys_dictionary_type.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.is_forbidden
     *
     * @return the value of sys_dictionary_type.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.is_forbidden
     *
     * @param isForbidden the value for sys_dictionary_type.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_type.version
     *
     * @return the value of sys_dictionary_type.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_type.version
     *
     * @param version the value for sys_dictionary_type.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}