package com.csj.gold.mobile.model;

import java.util.Date;

public class SysDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer dicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer dicPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_order
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer dicOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dic_value
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String dicValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.id
     *
     * @return the value of sys_dictionary.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.id
     *
     * @param id the value for sys_dictionary.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_name
     *
     * @return the value of sys_dictionary.dic_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_name
     *
     * @param dicName the value for sys_dictionary.dic_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDicName(String dicName) {
        this.dicName = dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_type
     *
     * @return the value of sys_dictionary.dic_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_type
     *
     * @param dicType the value for sys_dictionary.dic_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDicType(Integer dicType) {
        this.dicType = dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_pid
     *
     * @return the value of sys_dictionary.dic_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getDicPid() {
        return dicPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_pid
     *
     * @param dicPid the value for sys_dictionary.dic_pid
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDicPid(Integer dicPid) {
        this.dicPid = dicPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_order
     *
     * @return the value of sys_dictionary.dic_order
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getDicOrder() {
        return dicOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_order
     *
     * @param dicOrder the value for sys_dictionary.dic_order
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDicOrder(Integer dicOrder) {
        this.dicOrder = dicOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dic_value
     *
     * @return the value of sys_dictionary.dic_value
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dic_value
     *
     * @param dicValue the value for sys_dictionary.dic_value
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.remark
     *
     * @return the value of sys_dictionary.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.remark
     *
     * @param remark the value for sys_dictionary.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.create_date
     *
     * @return the value of sys_dictionary.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.create_date
     *
     * @param createDate the value for sys_dictionary.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.create_user
     *
     * @return the value of sys_dictionary.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.create_user
     *
     * @param createUser the value for sys_dictionary.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.update_date
     *
     * @return the value of sys_dictionary.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.update_date
     *
     * @param updateDate the value for sys_dictionary.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.update_user
     *
     * @return the value of sys_dictionary.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.update_user
     *
     * @param updateUser the value for sys_dictionary.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.is_del
     *
     * @return the value of sys_dictionary.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.is_del
     *
     * @param isDel the value for sys_dictionary.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.is_forbidden
     *
     * @return the value of sys_dictionary.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.is_forbidden
     *
     * @param isForbidden the value for sys_dictionary.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.version
     *
     * @return the value of sys_dictionary.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.version
     *
     * @param version the value for sys_dictionary.version
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}