package com.csj.gold.mobile.model;

import java.util.Date;

public class SysFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_path
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_size
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_category
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer fileCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String fileTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_link
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String fileLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.id
     *
     * @return the value of sys_file.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.id
     *
     * @param id the value for sys_file.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_name
     *
     * @return the value of sys_file.file_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_name
     *
     * @param fileName the value for sys_file.file_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_path
     *
     * @return the value of sys_file.file_path
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_path
     *
     * @param filePath the value for sys_file.file_path
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_size
     *
     * @return the value of sys_file.file_size
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_size
     *
     * @param fileSize the value for sys_file.file_size
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_type
     *
     * @return the value of sys_file.file_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_type
     *
     * @param fileType the value for sys_file.file_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_category
     *
     * @return the value of sys_file.file_category
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getFileCategory() {
        return fileCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_category
     *
     * @param fileCategory the value for sys_file.file_category
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileCategory(Integer fileCategory) {
        this.fileCategory = fileCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_title
     *
     * @return the value of sys_file.file_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_title
     *
     * @param fileTitle the value for sys_file.file_title
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.file_link
     *
     * @return the value of sys_file.file_link
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getFileLink() {
        return fileLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.file_link
     *
     * @param fileLink the value for sys_file.file_link
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.remark
     *
     * @return the value of sys_file.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.remark
     *
     * @param remark the value for sys_file.remark
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.is_forbidden
     *
     * @return the value of sys_file.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.is_forbidden
     *
     * @param isForbidden the value for sys_file.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.is_del
     *
     * @return the value of sys_file.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.is_del
     *
     * @param isDel the value for sys_file.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_date
     *
     * @return the value of sys_file.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_date
     *
     * @param createDate the value for sys_file.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.create_user
     *
     * @return the value of sys_file.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.create_user
     *
     * @param createUser the value for sys_file.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.update_date
     *
     * @return the value of sys_file.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.update_date
     *
     * @param updateDate the value for sys_file.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_file.update_user
     *
     * @return the value of sys_file.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_file.update_user
     *
     * @param updateUser the value for sys_file.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}