package com.csj.gold.mobile.model;

import java.util.Date;

public class UserProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.prouduct_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String prouductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.year_interest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Byte yearInterestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.day_intserest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Byte dayIntserestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.buy_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.expire_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.expire_intserest
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long expireIntserest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.prouduct_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long prouductType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long prouductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_product.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.id
     *
     * @return the value of user_product.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.id
     *
     * @param id the value for user_product.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.prouduct_name
     *
     * @return the value of user_product.prouduct_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getProuductName() {
        return prouductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.prouduct_name
     *
     * @param prouductName the value for user_product.prouduct_name
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProuductName(String prouductName) {
        this.prouductName = prouductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.year_interest_rate
     *
     * @return the value of user_product.year_interest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Byte getYearInterestRate() {
        return yearInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.year_interest_rate
     *
     * @param yearInterestRate the value for user_product.year_interest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setYearInterestRate(Byte yearInterestRate) {
        this.yearInterestRate = yearInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.day_intserest_rate
     *
     * @return the value of user_product.day_intserest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Byte getDayIntserestRate() {
        return dayIntserestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.day_intserest_rate
     *
     * @param dayIntserestRate the value for user_product.day_intserest_rate
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setDayIntserestRate(Byte dayIntserestRate) {
        this.dayIntserestRate = dayIntserestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.buy_date
     *
     * @return the value of user_product.buy_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.buy_date
     *
     * @param buyDate the value for user_product.buy_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.expire_date
     *
     * @return the value of user_product.expire_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.expire_date
     *
     * @param expireDate the value for user_product.expire_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.expire_intserest
     *
     * @return the value of user_product.expire_intserest
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getExpireIntserest() {
        return expireIntserest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.expire_intserest
     *
     * @param expireIntserest the value for user_product.expire_intserest
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setExpireIntserest(Long expireIntserest) {
        this.expireIntserest = expireIntserest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.prouduct_type
     *
     * @return the value of user_product.prouduct_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProuductType() {
        return prouductType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.prouduct_type
     *
     * @param prouductType the value for user_product.prouduct_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProuductType(Long prouductType) {
        this.prouductType = prouductType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.prouduct_id
     *
     * @return the value of user_product.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getProuductId() {
        return prouductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.prouduct_id
     *
     * @param prouductId the value for user_product.prouduct_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setProuductId(Long prouductId) {
        this.prouductId = prouductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.create_date
     *
     * @return the value of user_product.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.create_date
     *
     * @param createDate the value for user_product.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.create_user
     *
     * @return the value of user_product.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.create_user
     *
     * @param createUser the value for user_product.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.update_date
     *
     * @return the value of user_product.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.update_date
     *
     * @param updateDate the value for user_product.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.update_user
     *
     * @return the value of user_product.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.update_user
     *
     * @param updateUser the value for user_product.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.is_forbidden
     *
     * @return the value of user_product.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.is_forbidden
     *
     * @param isForbidden the value for user_product.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_product.is_del
     *
     * @return the value of user_product.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_product.is_del
     *
     * @param isDel the value for user_product.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}