package com.csj.gold.mobile.model;

import java.util.Date;

public class UserBankcard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.bank_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.card_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bankcard.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    private Integer isForbidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.id
     *
     * @return the value of user_bankcard.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.id
     *
     * @param id the value for user_bankcard.id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.bank_code
     *
     * @return the value of user_bankcard.bank_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.bank_code
     *
     * @param bankCode the value for user_bankcard.bank_code
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setBankCode(Integer bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.card_number
     *
     * @return the value of user_bankcard.card_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.card_number
     *
     * @param cardNumber the value for user_bankcard.card_number
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.user_id
     *
     * @return the value of user_bankcard.user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.user_id
     *
     * @param userId the value for user_bankcard.user_id
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.create_date
     *
     * @return the value of user_bankcard.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.create_date
     *
     * @param createDate the value for user_bankcard.create_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.update_date
     *
     * @return the value of user_bankcard.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.update_date
     *
     * @param updateDate the value for user_bankcard.update_date
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.update_user
     *
     * @return the value of user_bankcard.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.update_user
     *
     * @param updateUser the value for user_bankcard.update_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.create_user
     *
     * @return the value of user_bankcard.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.create_user
     *
     * @param createUser the value for user_bankcard.create_user
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.is_del
     *
     * @return the value of user_bankcard.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.is_del
     *
     * @param isDel the value for user_bankcard.is_del
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bankcard.is_forbidden
     *
     * @return the value of user_bankcard.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public Integer getIsForbidden() {
        return isForbidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bankcard.is_forbidden
     *
     * @param isForbidden the value for user_bankcard.is_forbidden
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
}