package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.ProductInterestInfo;

public interface ProductInterestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(ProductInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(ProductInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    ProductInterestInfo selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<ProductInterestInfo> selectByParameters(ProductInterestInfo productInterestInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(ProductInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_interest_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(ProductInterestInfo record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}