package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.ProductPriceInfo;

public interface ProductPriceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(ProductPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(ProductPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    ProductPriceInfo selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<ProductPriceInfo> selectByParameters(ProductPriceInfo productPriceInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(ProductPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(ProductPriceInfo record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}