package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.RoleAuthority;

public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    RoleAuthority selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<RoleAuthority> selectByParameters(RoleAuthority roleAuthority);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(RoleAuthority record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}