package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.ScheduleHistory;

public interface ScheduleHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(ScheduleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(ScheduleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    ScheduleHistory selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<ScheduleHistory> selectByParameters(ScheduleHistory scheduleHistory);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(ScheduleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_history
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(ScheduleHistory record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}