package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.SysAccoutTransactions;

public interface SysAccoutTransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(SysAccoutTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(SysAccoutTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    SysAccoutTransactions selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<SysAccoutTransactions> selectByParameters(SysAccoutTransactions sysAccoutTransactions);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(SysAccoutTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_accout_transactions
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(SysAccoutTransactions record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}