package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.SysContact;

public interface SysContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(SysContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(SysContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    SysContact selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<SysContact> selectByParameters(SysContact sysContact);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(SysContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_contact
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(SysContact record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}