package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.SysDictionaryType;

public interface SysDictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(SysDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(SysDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    SysDictionaryType selectByPrimaryKey(Integer id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<SysDictionaryType> selectByParameters(SysDictionaryType sysDictionaryType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(SysDictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(SysDictionaryType record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Integer id);
}