package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.SysMobileMenu;

public interface SysMobileMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(SysMobileMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(SysMobileMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    SysMobileMenu selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<SysMobileMenu> selectByParameters(SysMobileMenu sysMobileMenu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(SysMobileMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_mobile_menu
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(SysMobileMenu record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}