package com.csj.gold.mobile.dao;

import java.util.List;

import com.csj.gold.mobile.model.UserProduct;

public interface UserProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insert(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int insertSelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    UserProduct selectByPrimaryKey(Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_type
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    List<UserProduct> selectByParameters(UserProduct userProduct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKeySelective(UserProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_product
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateByPrimaryKey(UserProduct record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Fri Dec 11 18:10:49 CST 2015
     */
    int updateForbiddenByPrimaryKey(Long id);
}