package com.csj.gold.mobile.common;

public interface MobileConstants {
	
	String REQUEST_TYPE_NAME = "type";
	String REQUEST_TYPE_VALUE_CHANGE_KEY = "1";//交换密钥
	String REQUEST_TYPE_VALUE_TRANS = "2";//正常交易
	String REQUEST_PARAMS_NAME  = "params";
	String IDEA_KEY_NAME = "p2pIdeaKey";
	
	String TRAN_NO_LOGIN = "1001";//登录请求
	String TRAN_NO_DEPTLIST = "1002";//部门List请求
	String TRAN_NO_BANKLIST = "1003";//银行List请求
	String TRAN_NO_LOGOUT = "1004";//注销请求
	String TRAN_NO_CHANGEPASSWORD = "1005";//密码修改请求
	String TRAN_NO_PRODUCTLIST = "1006";//产品List请求
	String TRAN_NO_TRACK = "1007";//日迹
	String TRAN_NO_SALES_VOLUME = "1008";//提交销量
	String TRAN_NO_SALES_VOLUME_HISTORY = "1009";//历史销量
	String TRAN_NO_TRACK_INFO = "1010";//获取日迹信息
	String TRAN_NO_SALES_VOLUME_REVOKE = "1011";//撤销销量
	String TRAN_NO_SALES_VOLUME_RECYCLE_BIN = "1012";//回收箱销量
	String TRAN_NO_PERTRACK_HISTORY = "1013";//历史日迹
	String TRAN_NO_DICTIONARY_LIST = "1014";//字典数据
	
	
	String TRAN_NO_REGISTER = "002";//注册请求
	String TRAN_NO_FORGOTPASSWORD="003";//找回密码请求
	String TRAN_NO_UPDATEPASSWORD="004";//修改密码请求
	String TRAN_NO_ACCOUNT_ASSETS="005";//账户资产请求
	String TRAN_NO_MY_WEALTH="006";//我的财富
	String TRAN_NO_MY_INFORMATION="007";//安全设置
	String TRAN_NO_INVESTMENT_PROJECT="008";//投资项目
	String TRAN_NO_TRANSACTION_RECORDS="009";//交易记录
	String TRAN_NO_NEXT_PARAGRAPH="010";//下期回款
	String TRAN_NO_AUTHENTICATE="011";//实名认证
	String TRAN_NO_BIND_TELPHONE="012";//绑定手机号码请求
	String TRAN_NO_BIND_TELPHONE_CHECKED="013";//手机号码验证成功
	String TRAN_NO_BIND_EMAIL="014";//绑定邮箱请求
	String TRAN_NO_BID_PLAN="015";//标的
	String TRAN_NO_EXIT="016";//退出登录
	String TRAN_NO_CHECK_USER="017";//检查用户是否登陆
	String TRAN_NO_RESET_PASSWORD="018";//重置密码
	String TRAN_NO_BID_DETAIL="019";//标的还款计划
	String TRAN_NO_BID_INFO="020";//标的投资人记录信息
	String TRAN_NO_BID_BIDING="021";//个人标的投资
	String TRAN_NO_BID_BIDINGINFO="022";//个人投资前置信息信息
	String TRAN_NO_ABOUT_WE="023";//关于我们
	String TRAN_NO_BID_DETAIL_INFO="024";//标的详情
	String TRAN_NO_ARTICLE_LIST="026";//文章列表
	String TRAN_NO_ARTICLE_DIS="027";//文章详情
	String TRAN_NO_MANAGE_MONEY_PLAN="028";//理财计划
	
	String RESULT_CODE_SUCCESS = "2001";
	String RESULT_CODE_SUCCESS_DESC = "成功!";
	
	String RESULT_CODE_EXIT_SUCCESS="2002";
	String RESULT_CODE_EXIT_SUCCESS_DESC="成功退出登录";

	String RESULT_CODE_FAULT="3000";
	String RESULT_CODE_FAULT_DESC="失败!";
	
	String RESULT_CODE_ERROR_EXIST = "3001";
	String RESULT_CODE_ERROR_EXIST_DESC = "未知错误!";
	
	String RESULT_CODE_SEND_CHECKCODE="3002";
	String RESULT_CODE_SEND_CHECKCODE_DESC="短信发送失败";
	
	String RESULT_CODE_CHECKCODE="3003";
	String RESULT_CODE_CHECKCODE_DESC="验证码失效,请重新发送";
	
//	String RESULT_CODE_TYPE_ERROR = "3004";
//	String RESULT_CODE_TYPE_ERROR_DESC = "请求类型不正确!";
//
//	String RESULT_CODE_PARAMS_NO_EXIST = "3003";
//	String RESULT_CODE_PARAMS_NO_EXIST_DESC = "参数params不能为空!";
//
//	String RESULT_CODE_PARAMS_FORMAT_ERROR = "3004";
//	String RESULT_CODE_PARAMS_FORMAT_ERROR_DESC = "参数params格式不对!";
//
//	String RESULT_CODE_NO_CONTROL = "3005";
//	String RESULT_CODE_NO_CONTROL_DESC = "spring中没有配置mobile controller类！";
//
//	String RESULT_CODE_TRAN_CLASS_NO_EXIST = "3006";
//	String RESULT_CODE_TRAN_CLASS_NO_EXIST_DESC = "交易类不存在!";
//
//	String RESULT_CODE_TRAN_CLASS_NO_IMPLEMENTS = "3007";
//	String RESULT_CODE_TRAN_CLASS_NO_IMPLEMENTS_DESC = "交易类没有实现交易接口!";
//
//	String RESULT_CODE_PARAMS_TYPE_NO_EXIST = "3008";
//	String RESULT_CODE_PARAMS_TYPE_NO_EXIST_DESC = "交易参数类不存在!";
//	
//	String RESULT_CODE_LOGIN_TIMES = "3009";
//	String RESULT_CODE_LOGIN_TIMES_DESC = "登录失败连续超过5次，请稍后再试";
//	
//	String RESULT_CODE_LOGIN_FORBIDDEN="3010";
//	String RESULT_CODE_LOGIN_FORBIDDEN_DESC="该用户已被禁用,无法登录！";
//	
//	String RESULT_CODE_ERROR="3011";
//	String RESULT_CODE_ERROR_DESC="验证码输入错误！";
//	
//	String RESULT_CODE_DATA_EMPTY="3012";
//	String RESULT_CODE_DATA_EMPTY_DESC="Data is Empty!";
//	
//	
//	String RESULT_CODE_NEWPASSWORD_NULL="3013";
//	String RESULT_CODE_NEWPASSWORD_NULL_DESC="新密码不能为空";
//	
//	String RESULT_CODE_USERNAME_EXIST="0012";
//	String RESULT_CODE_USERNAME_EXIST_DESC="该用户名已经存在";
//	
//	String RESULT_CODE_USERNAME_PASSWORD_ERROR="3013";
//	String RESULT_CODE_USERNAME_PASSWORD_ERROR_DESC="用户名或密码错误";
//	
//	String RESULT_CODE_USERNAME_EMPTY="3014";
//	String RESULT_CODE_USERNAME_EMPTY_DESC="用户名不能为空";
//	
//	String RESULT_CODE_USERNAME_NOT_EXIST="3015";
//	String RESULT_CODE_USERNAME_NOT_EXIST_DESC="用户名不存在";
//	
//	String RESULT_CODE_PASWORD_ERROR="3016";
//	String RESULT_CODE_PASWORD_ERROR_DESC="密码错误";
//	
//	String RESULT_CODE_NO_RIGHT_ENTER="3017";
//	String RESULT_CODE_NO_RIGHT_ENTER_DESC="无权限访问";
//	
//	String RESULT_CODE_USERNAME_NO_EXIST="3018";
//	String RESULT_CODE_USERNAME_NO_EXIST_DESC="该账户不存在";
//	
//	String RESULT_CODE_UPDATEPASSWORD_SUCCESS="2019";
//	String RESULT_CODE_UPDATEPASSWORD_SUCCESS_DESC="登录密码修改成功";
//	
//	String RESULT_CODE_LOGIN_NO_EXIST="3020";
//	String RESULT_CODE_LOGIN_NO_EXIST_DESC="您未登录，请先登录";
//	
//	String RESULT_CODE_DATA_IS_EMPTY="3021";
//	String RESULT_CODE_DATA_IS_EMPTY_DESC="参数为空！";
//	
//	String RESULT_CODE_WAS_LOGIN="3022";
//	String RESULT_CODE_WAS_LOGIN_DESC="当前帐号已登陆！";
//	
//	String RESULT_CODE_RESET_PASSWORD_FAILED="3023";
//	String RESULT_CODE_RESET_PASSWORD_FAILED_DESC="重置密码失败";
//	
//	String RESULT_CODE_DEPT_DATA_EMPTY="3024";
//	String RESULT_CODE_DEPT_DATA_EMPTY_DESC="没有部门数据,请联系管理员！";
//	
//
//	
//	String RESULT_CODE_AUTHENTICATE_CHECKED="0021";
//	String RESULT_CODE_AUTHENTICATE_CHECKED_DESC="该身份证已被认证！";
//	
//	String RESULT_CODE_AUTHENTICATE_CHECKED_FAILED="0022";
//	String RESULT_CODE_AUTHENTICATE_CHECKED_FAILED_DESC="实名认证失败";
//	
//	String RESULT_CODE_AUTHENTICATE_CHECKED_SUCCESS="0023";
//	String RESULT_CODE_AUTHENTICATE_CHECKED_SUCCESS_DESC="实名认证成功";
//	
//	String RESULT_CODE_TELPHONE_CODE_WRONG="0024";
//	String RESULT_CODE_TELPHONE_CODE_WRONG_DESC="手机验证码错误";
//	
//	String RESULT_CODE_TELPHONE_ALREADY_REGISTER="0025";
//	String RESULT_CODE_TELPHONE_ALREADY_REGISTER_DESC="该手机号已被其他用户注册";
//	
//	String RESULT_CODE_TELPHONE_CHECK_SUCCESS="0026";
//	String RESULT_CODE_TELPHONE_CHECK_SUCCESS_DESC="手机验证成功";
//	
//	String RESULT_CODE_TELPHONE_CHECK_FAILED="0027";
//	String RESULT_CODE_TELPHONE_CHECK_FAILED_DESC="手机验证失败";
//	
//	String RESULT_CODE_EMAIL_ALREADY_REGISTER="0029";
//	String RESULT_CODE_EMAIL_ALREADY_REGISTER_DESC="该邮箱已被其他用户注册";
//	
//	String RESULT_CODE_EMAIL_SEND_SUCCESS="0030";
//	String RESULT_CODE_EMAIL_SEND_SUCCESS_DESC="邮件发送成功";
//	
//	String RESULT_CODE_EMAIL_SEND_FAILED="0031";
//	String RESULT_CODE_EMAIL_SEND_FAILED_DESC="邮件发送失败";
//	
//	String RESULT_CODE_EMAIL_CHECKED_SUCCESS="0032";
//	String RESULT_CODE_EMAIL_CHECKED_SUCCESS_DESC="邮件验证成功";
//	
//	String RESULT_CODE_EMAIL_CHECKED_FAILED="0033";
//	String RESULT_CODE_EMAIL_CHECKED_FAILED_DESC="邮件验证失败";
//	
//	String RESULT_CODE_NEED_RESEND_KEY="0035";
//	String RESULT_CODE_NEED_RESEND_KEY_DESC="需要重新发送密钥！";
//	
//	String RESULT_CODE_KEY_ERROR="0036";
//	String RESULT_CODE_KEY_ERROR_DESC="mobile对称密钥不正确!";
//	
//	String RESULT_CODE_DESCRYPT_ERROR="0037";
//	String RESULT_CODE_DESCRYPT_ERROR_DESC="数据解密错误!";
//	
//	String RESULT_CODE_NO_IDEA_KEY_ERROR="0038";
//	String RESULT_CODE_NO_IDEA_KEY_ERROR_DESC="数据解密错误!";
//	
//	String RESULT_CODE_REGISTER_SUCCESS="0014";
//	String RESULT_CODE_REGISTER_SUCCESS_DESC="用户名注册成功";
//	
//	String RESULT_CODE_PLATFORM_VALIDATION_FAILED="0015";
//	String RESULT_CODE_PLATFORM_VALIDATION_FAILED_DESC="云平台验证失败";
//	
//	String RESULT_CODE_TELPHONE_NO_EXIST="0016";
//	String RESULT_CODE_TELPHONE_NO_EXIST_DESC="该会员没有注册手机号";
//	
//    String RESULT_CODE_NO_TELPHONE="0017";
//    String RESULT_CODE_NO_TELPHONE_DESC="请输入手机号";
//	
//	String RESULT_CODE_PAY_SUCCESS = "0040";
//	String RESULT_CODE_PAY_SUCCESS_DESC = "支付成功!";
	

	
	String PARAMS_NAME = "paramsStr";

	
}

